---
title: "iDAS: Interpretable Differential Abundance Signature"
date: "`r Sys.Date()`"
author:
- name: Lijia Yu
  affiliation:
  - School of Mathematics and Statistics, The University of Sydney, NSW 2006, Australia;
  - Sydney Precision Data Science Centre, University of Sydney, NSW 2006, Australia
  - Charles Perkins Centre, The University of Sydney, NSW 2006, Australia
  - Computational Systems Biology Unit, Children’s Medical Research Institute, Faculty of Medicine and Health, University of Sydney, NSW 2145, Australia
- name: Yingxin Lin
  affiliation:
  - Department of Biostatistics, Yale University, New Haven, CT 208034, USA
- name: Xiangnan Xu
  affiliation:
  - School of Business and Economics, Humboldt-Universität zu Berlin, Berlin 10099, Germany
- name: Pengyi Yang
  affiliation:
  - Computational Systems Biology Unit, Children’s Medical Research Institute, Faculty of Medicine and Health, University of Sydney, NSW 2145, Australia;
  - School of Mathematics and Statistics, The University of Sydney, NSW 2006, Australia;
  - Sydney Precision Data Science Centre, University of Sydney, NSW 2006, Australia;
  - Charles Perkins Centre, The University of Sydney, NSW 2006, Australia;
  - Laboratory of Data Discovery for Health Limited (D24H), Science Park, Hong Kong SAR, China.
- name: Jean Yang
  affiliation:
  - School of Mathematics and Statistics, The University of Sydney, NSW 2006, Australia;
  - Sydney Precision Data Science Centre, University of Sydney, NSW 2006, Australia;
  - Charles Perkins Centre, The University of Sydney, NSW 2006, Australia;
  - Laboratory of Data Discovery for Health Limited (D24H), Science Park, Hong Kong SAR, China.
output:
  BiocStyle::html_document:
    toc_float: true
    toc_depth: 3
    theme: united
    highlight: tango
    code-fold: false
    code-tools: true
    embed-resources: true
    number_sections: false
  BiocStyle::pdf_document: 
    number_sections: false
package: iDAS
vignette: |
    %\VignetteIndexEntry{iDAS tutorial: simulation}
    %\VignetteEncoding{UTF-8}
    %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 80
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Introduction




```{r}
library(iDAS)

set.seed(123)
Z <- matrix(rnorm(1000), ncol = 10)
colnames(Z)=paste0("gene",1:10)
factor1 <- as.factor(rep(1:2, each = 5))
factor2 <- as.factor(rep(1:2, times = 5))
factor3 <- as.factor(rep(1:2, length.out = 10))

# Run the differential analysis using iDAS
result <- iDAS(
  Z, factor1, factor2, factor3,
  model_fit_function = "lm",
  test_function = "parametric",
  pval_quantile_cutoff = 0.02,
  pval_cutoff_full = 0.05,
  pval_cutoff_interaction = 0.01,
  pval_cutoff_factor1 = 0.01,
  pval_cutoff_factor2 = 0.01,
  pval_cutoff_factor3 = 0.01,
  pval_cutoff_int12 = 0.01,
  pval_cutoff_int13 = 0.01,
  pval_cutoff_int23 = 0.01,
  pval_cutoff_int123 = 0.01
)

# Inspect results
head(result$pval_matrix)
head(result$stat_matrix)
head(result$class_df)

```



## Demo example

```{r setup}


demo <- readRDS(system.file("extdata", "melanoma_example.rds", package = "iDAS"))
```

just a test, haven't finished.
